[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sicat_protocol = "F5K84FMkCoSMpNP967fwAh7ZijrdNtMKv5dwzjaxcuPY"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
